# Generated by Django 5.2.17 on 2026-08-31 11:00

import django.db.models.deletion
import screening.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('patient_reference', models.CharField(db_index=True, help_text='Non-identifying case reference, for example DEMO-001.', max_length=32)),
                ('xray_image', models.ImageField(upload_to=screening.models.xray_upload_path)),
                ('quality_status', models.CharField(choices=[('ACCEPTABLE', 'Acceptable'), ('DEGRADED', 'Degraded'), ('INVALID', 'Invalid')], max_length=16)),
                ('quality_message', models.CharField(blank=True, max_length=200)),
                ('blur_score', models.FloatField(blank=True, help_text='Variance of the Laplacian. Lower values indicate a blurrier image.', null=True)),
                ('brightness_mean', models.FloatField(blank=True, help_text='Mean pixel intensity of the greyscale image, 0 to 255.', null=True)),
                ('predicted_label', models.CharField(choices=[('LIKELY_TB', 'Likely TB'), ('UNLIKELY_TB', 'Unlikely TB')], max_length=16)),
                ('tb_probability', models.DecimalField(decimal_places=4, max_digits=5)),
                ('decision_threshold', models.DecimalField(decimal_places=3, max_digits=4)),
                ('triage_level', models.CharField(choices=[('LOW', 'Low suspicion'), ('MEDIUM', 'Medium suspicion'), ('HIGH', 'High suspicion')], db_index=True, max_length=8)),
                ('triage_justification', models.TextField(blank=True)),
                ('triage_low_medium_threshold', models.DecimalField(decimal_places=3, max_digits=4)),
                ('triage_medium_high_threshold', models.DecimalField(decimal_places=3, max_digits=4)),
                ('gradcam_image', models.ImageField(blank=True, null=True, upload_to=screening.models.heatmap_upload_path)),
                ('gradcam_status', models.CharField(choices=[('GENERATED', 'Generated'), ('FAILED', 'Failed'), ('NOT_ATTEMPTED', 'Not attempted')], default='NOT_ATTEMPTED', max_length=16)),
                ('model_version', models.CharField(max_length=64)),
                ('inference_ms', models.PositiveIntegerField(blank=True, help_text='Inference time on this machine, used to evidence CPU suitability.', null=True)),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending review'), ('REVIEWED', 'Reviewed'), ('FOLLOW_UP', 'Follow-up required')], db_index=True, default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Prediction record',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['review_status', '-created_at'], name='pred_review_created_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('tb_probability__gte', 0), ('tb_probability__lte', 1)), name='tb_probability_within_zero_to_one'), models.CheckConstraint(condition=models.Q(('triage_low_medium_threshold__lt', models.F('triage_medium_high_threshold'))), name='triage_thresholds_ordered')],
            },
        ),
        migrations.CreateModel(
            name='ReviewNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField()),
                ('status_set', models.CharField(choices=[('PENDING', 'Pending review'), ('REVIEWED', 'Reviewed'), ('FOLLOW_UP', 'Follow-up required')], help_text='Review status the reviewer set when this note was written.', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_notes', to='screening.predictionrecord')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
